export const projects = [
  {
    id: 1,
    title: "NFT Project",
    img: "./images/nft.png",
    source: "https://github.com/benjaminluan/Benjamin-Internship",
    preview: "https://internship-nftproject.vercel.app/",
    para: "Fetched Api and dynamically displayed data and installation of carousels.",
    language: "HTML, CSS, Javascript, React",
  },
  {
    id: 2,
    title: "E-Commerce Library Website",
    img: "./images/Library.png",
    source: "https://github.com/benjaminluan/Library-Project",
    preview: "https://library-benjaminluan.vercel.app/",
    para: "A project with the intention to grasp a better understanding of HTML, CSS and Javascript.",
    language: "HTML, CSS, Javascript, React",
  },
  {
    id: 3,
    title: "LoL Info",
    img: "./images/league.png",
    source: "https://github.com/benjaminluan/League-react",
    preview: "https://league-react.vercel.app/",
    para: "A league of Legends fan-made project that can filter and showcase champions description.",
    language: "HTML, CSS, Javascript, React",
  },

  {
    id: 4,
    title: "Spotify Clone",
    img: "./images/spotify.png",
    source: "https://github.com/benjaminluan/Spotify-Clone",
    preview: "https://spotify-clone-lovat-phi.vercel.app/",
    para: "Spotify Clone",
    language: "HTML, CSS, Javascript, React",
  },
  {
    id: 5,
    title: "E-Portfolio",
    img: "./images/portfolio.png",
    source: "https://github.com/benjaminluan/Portfolio",
    preview: "https://benjaminluan.github.io/Portfolio/",
    para: "A project with the intention to grasp a better understanding of HTML, CSS and Javascript.",
    language: "HTML, CSS, Javascript",
  },
  {
    id: 6,
    title: "Search Engine",
    img: "./images/google.png",
    source: "https://github.com/benjaminluan/Google-Clone",
    preview: "https://google-clone-liart-delta.vercel.app/",
    para: "Google Clone",
    language: "HTML, CSS, Javascript, React",
  },
  {
    id: 7,
    title: "1:1 Treact Template",
    img: "./images/treact.png",
    source: "https://github.com/benjaminluan/Treact-Project",
    preview: "https://benjaminluan.github.io/Treact-Project/",
    para: "A project with the intention to grasp a better understanding of HTML, CSS and Javascript.",
    language: "HTML, CSS ",
  },
];
